#!/bin/bash
# Force deployment to PythonAnywhere with aggressive cache clearing

echo "🚀 FORCING DEPLOYMENT TO PYTHONANYWHERE..."
echo ""
echo "Run these commands on PythonAnywhere (SSH or Bash console):"
echo ""
echo "# 1. Navigate to project directory"
echo "cd /home/adamcordova/AGTDesigner"
echo ""
echo "# 2. Pull latest code"
echo "git fetch origin main"
echo "git reset --hard origin/main"
echo ""
echo "# 3. Clear Python cache aggressively"
echo "find . -type d -name '__pycache__' -exec rm -r {} + 2>/dev/null || true"
echo "find . -type f -name '*.pyc' -delete"
echo ""
echo "# 4. Force reload web app"
echo "touch /var/www/agtpricetags_pythonanywhere_com_wsgi.py"
echo ""
echo "# 5. Verify latest commit"
echo "git log --oneline -1"
echo ""
echo "Expected commit: b7c70aba Add performance timing logs to identify bottlenecks"
echo ""
echo "If commit doesn't match, run: git pull origin main --force"
