#!/bin/bash
# NUCLEAR OPTION: Complete database reset on PythonAnywhere

echo "💥 NUCLEAR DATABASE FIX FOR PYTHONANYWHERE"
echo "=========================================="
echo ""
echo "⚠️  WARNING: This will completely reset your database!"
echo ""

echo "🚀 STEP-BY-STEP NUCLEAR FIX:"
echo "============================"
echo ""
echo "1️⃣  UPLOAD FRESH DATABASE:"
echo "   • Go to https://www.pythonanywhere.com"
echo "   • Files tab → /home/adamcordova/AGTDesigner"
echo "   • Upload: production_database_fix_20251012_142615.zip"
echo ""
echo "2️⃣  NUCLEAR RESET IN BASH CONSOLE:"
echo "   Run these commands:"
echo ""
echo "   # Kill everything"
echo "   pkill -f python"
echo "   pkill -f flask"
echo "   sleep 5"
echo ""
echo "   # Go to project directory"
echo "   cd ~/AGTDesigner"
echo ""
echo "   # NUCLEAR: Remove ALL database files"
echo "   rm -rf uploads/*.db*"
echo "   rm -rf uploads/backups_old"
echo "   rm -rf uploads/*.wal"
echo "   rm -rf uploads/*.shm"
echo ""
echo "   # Create fresh uploads directory"
echo "   mkdir -p uploads"
echo ""
echo "   # Extract fresh database"
echo "   unzip -o production_database_fix_20251012_142615.zip"
echo "   mv product_database_AGT_Bothell.db uploads/"
echo ""
echo "   # Fix permissions"
echo "   chmod 644 uploads/product_database_AGT_Bothell.db"
echo "   chown adamcordova:adamcordova uploads/product_database_AGT_Bothell.db"
echo ""
echo "   # Test database"
echo "   sqlite3 uploads/product_database_AGT_Bothell.db \"SELECT COUNT(*) FROM products;\""
echo ""
echo "3️⃣  RESTART WEB APP:"
echo "   • Web tab → Reload button"
echo "   • Wait 60 seconds"
echo ""
echo "4️⃣  TEST:"
echo "   • Visit https://www.agtpricetags.com"
echo "   • Check browser console for errors"
echo "   • Verify product counts show up"
echo ""

echo "💡 If STILL not working, try this alternative:"
echo "   • Go to Files tab"
echo "   • Navigate to uploads/"
echo "   • Delete ALL .db files manually"
echo "   • Upload fresh database zip"
echo "   • Extract manually in Files tab"
echo ""

echo "🔧 DEBUG COMMANDS (if needed):"
echo "   # Check what's running"
echo "   ps aux | grep python"
echo ""
echo "   # Check database file"
echo "   ls -la uploads/product_database_AGT_Bothell.db"
echo ""
echo "   # Test database directly"
echo "   sqlite3 uploads/product_database_AGT_Bothell.db \"PRAGMA integrity_check;\""
echo ""

echo "✅ This NUCLEAR option WILL fix the database lock issue!"
