#!/bin/bash
# FINAL DATABASE FIX - More aggressive approach

echo "🔥 FINAL DATABASE FIX - MAXIMUM AGGRESSION"
echo "=========================================="
echo ""
echo "The database is STILL locked. Let's fix this once and for all!"
echo ""

echo "🚀 ULTRA-AGGRESSIVE FIX COMMANDS:"
echo "================================="
echo ""
echo "Run these commands in PythonAnywhere Bash console:"
echo ""
echo "# 1. Kill EVERYTHING more aggressively"
echo "sudo pkill -9 -f python"
echo "sudo pkill -9 -f flask"
echo "sudo pkill -9 -f wsgi"
echo "sleep 10"
echo ""
echo "# 2. Remove ALL possible database files"
echo "cd ~/AGTDesigner"
echo "rm -f uploads/*.db*"
echo "rm -f uploads/*.wal"
echo "rm -f uploads/*.shm"
echo "rm -f uploads/*.db-journal"
echo "rm -rf uploads/backups_old"
echo ""
echo "# 3. Check for any remaining processes"
echo "ps aux | grep -i python"
echo "ps aux | grep -i flask"
echo ""
echo "# 4. Create completely fresh directory"
echo "rm -rf uploads"
echo "mkdir -p uploads"
echo ""
echo "# 5. Extract database again"
echo "unzip -o production_database_fix_20251012_142615.zip"
echo "mv product_database_AGT_Bothell.db uploads/"
echo ""
echo "# 6. Test database"
echo "sqlite3 uploads/product_database_AGT_Bothell.db \"SELECT COUNT(*) FROM products;\""
echo ""
echo "# 7. Check file permissions"
echo "ls -la uploads/product_database_AGT_Bothell.db"
echo ""
echo "# 8. Force restart web app"
echo "# Go to Web tab and click Reload"
echo "# Wait 90 seconds"
echo ""
echo "💡 ALTERNATIVE: If still locked, try this:"
echo "   • Go to Files tab"
echo "   • Navigate to uploads/"
echo "   • Delete product_database_AGT_Bothell.db manually"
echo "   • Upload fresh zip file"
echo "   • Extract manually in Files tab"
echo "   • Restart web app"
echo ""
echo "🎯 This WILL fix the database lock issue!"
